# Generated by Django 5.2.4 on 2025-08-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
